services:
  accounts:
    image: "giaphu04/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - giaphu
  loans:
    image: "giaphu04/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - giaphu
  cards:
    image: "giaphu04/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - giaphu
networks:
  giaphu:
    driver: "bridge"

